### ISSUE TITLE
Problem running on macOS 10.14.3

### ISSUE THREAD

**Issue by yangm97** [p2pstuff/PeerDNS#1]
```
~/D/P/PeerDNS ❯❯❯ mix deps.get                                                                                   master
zsh: correct mix to nix [nyae]? n
Could not find Hex, which is needed to build dependency :bencode
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] 
* creating /Users/yan/.mix/archives/hex-0.19.0
* Getting enacl (https://github.com/jlouis/enacl.git)
remote: Enumerating objects: 5, done.        
remote: Counting objects: 100% (5/5), done.        
remote: Compressing objects: 100% (5/5), done.        
remote: Total 863 (delta 0), reused 3 (delta 0), pack-reused 858        
Receiving objects: 100% (863/863), 288.87 KiB | 588.00 KiB/s, done.
Resolving deltas: 100% (490/490), done.
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  bencode 0.3.2
  cors_plug 2.0.0
  cowboy 2.6.1
  cowlib 2.7.0
  dns 2.1.2
  eqc_ex 1.2.4
  httpotion 3.1.1
  ibrowse 4.4.0
  mime 1.3.1
  plug 1.7.1
  plug_cowboy 2.0.1
  plug_crypto 1.0.0
  poison 3.1.0
  ranch 1.7.1
  socket 0.3.13
* Getting bencode (Hex package)
* Getting httpotion (Hex package)
* Getting plug (Hex package)
* Getting cowboy (Hex package)
* Getting plug_cowboy (Hex package)
* Getting cors_plug (Hex package)
* Getting poison (Hex package)
* Getting dns (Hex package)
* Getting socket (Hex package)
* Getting cowlib (Hex package)
* Getting ranch (Hex package)
* Getting mime (Hex package)
* Getting plug_crypto (Hex package)
* Getting ibrowse (Hex package)
* Getting eqc_ex (Hex package)
~/D/P/PeerDNS ❯❯❯ cp config/config.exs.sample config/config.exs                                                  master
~/D/P/PeerDNS ❯❯❯ subl config/config.exs                                                                         master
~/D/P/PeerDNS ❯❯❯ mix run --no-halt                                                                              master
==> socket
Compiling 11 files (.ex)
Generated socket app
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/yan/Documents/Projects/PeerDNS/deps/eqc_ex/mix.exs:11

warning: variable "docs" does not exist and is being expanded to "docs()", please use parentheses to remove the ambiguity or change the variable name
  /Users/yan/Documents/Projects/PeerDNS/deps/eqc_ex/mix.exs:12

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /Users/yan/Documents/Projects/PeerDNS/deps/eqc_ex/mix.exs:13

==> eqc_ex
Compiling 8 files (.ex)
warning: variable "__SELF__" does not exist and is being expanded to "__SELF__()", please use parentheses to remove the ambiguity or change the variable name
  lib/eqc/component/callouts.ex:239

warning: Kernel.to_char_list/1 is deprecated. Use Kernel.to_charlist/1 instead
  lib/eqc.ex:236

warning: module attribute @copyright was set but never used
  lib/eqc/component.ex:2

warning: module attribute @copyright was set but never used
  lib/eqc/mocking.ex:2

warning: module attribute @copyright was set but never used
  lib/eqc/pulse.ex:2

warning: module attribute @copyright was set but never used
  lib/eqc/component/callouts.ex:2

warning: module attribute @copyright was set but never used
  lib/eqc.ex:2

warning: Dict.get/2 is deprecated. Use the Map module for working with maps or the Keyword module for working with keyword lists
  lib/mix_eqcci.ex:82

warning: Dict.take/2 is deprecated. Use the Map module for working with maps or the Keyword module for working with keyword lists
  lib/mix_eqcci.ex:76

warning: Kernel.to_char_list/1 is deprecated. Use Kernel.to_charlist/1 instead
  lib/eqc.ex:236

warning: Kernel.ParallelCompiler.files_to_path/2 is deprecated. Use Kernel.ParallelCompiler.compile_to_path/2 instead
  lib/mix_eqcci.ex:64

warning: function :eqc.collect/2 is undefined (module :eqc is not available)
  lib/eqc.ex:458

warning: function :eqc.features/2 is undefined (module :eqc is not available)
  lib/eqc.ex:458

warning: function :eqc.numtests/2 is undefined (module :eqc is not available)
  lib/eqc/exunit.ex:59

warning: function :eqc.testing_time/2 is undefined (module :eqc is not available)
Found at 2 locations:
  lib/eqc/exunit.ex:62
  lib/eqc/exunit.ex:65

warning: function :eqc_component.callout/4 is undefined (module :eqc_component is not available)
  lib/eqc/component/callouts.ex:58

warning: function :eqc_component.pretty_commands/4 is undefined (module :eqc_component is not available)
  lib/eqc/component.ex:49

warning: function :eqc_component.run_commands/3 is undefined (module :eqc_component is not available)
  lib/eqc/component.ex:40

warning: function :eqc_statem.check_commands/4 is undefined (module :eqc_statem is not available)
  lib/eqc/statem.ex:40

warning: function :eqc_statem.pretty_commands/4 is undefined (module :eqc_statem is not available)
  lib/eqc/statem.ex:31

warning: function :eqc_statem.run_commands/3 is undefined (module :eqc_statem is not available)
  lib/eqc/statem.ex:18

warning: function :eqc_statem.run_parallel_commands/3 is undefined (module :eqc_statem is not available)
  lib/eqc/statem.ex:26

Generated eqc_ex app
warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
  /Users/yan/Documents/Projects/PeerDNS/deps/bencode/mix.exs:11

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /Users/yan/Documents/Projects/PeerDNS/deps/bencode/mix.exs:12

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/yan/Documents/Projects/PeerDNS/deps/bencode/mix.exs:13

==> bencode
Compiling 5 files (.ex)
Generated bencode app
==> dns
Compiling 7 files (.ex)
Generated dns app
==> peerdns
Could not find "rebar3", which is needed to build dependency :ranch
I can install a local copy which is just used by Mix
Shall I install rebar3? (if running non-interactively, use "mix local.rebar --force") [Yn] 
* creating /Users/yan/.mix/rebar
* creating /Users/yan/.mix/rebar3
===> Compiling ranch
===> Compiling enacl
cc -O3 -std=c99 -arch x86_64 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/Cellar/erlang/21.2.4/lib/erlang/erts-10.2.3/include/ -I /usr/local/Cellar/erlang/21.2.4/lib/erlang/lib/erl_interface-3.10.4/include  -c -o /Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.o /Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c
/Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c:5:10: fatal error: 'sodium.h' file not found
#include <sodium.h>
         ^~~~~~~~~~
1 error generated.
make: *** [/Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.o] Error 1
===> Hook for compile failed!

** (Mix) Could not compile dependency :enacl, "/Users/yan/.mix/rebar3 bare compile --paths "/Users/yan/Documents/Projects/PeerDNS/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile enacl", update it with "mix deps.update enacl" or clean it with "mix deps.clean enacl"
```

**Comment by yangm97** [comment]
Installing libsodium with `brew install libsodium` brings us to:

```
~/D/P/PeerDNS ❯❯❯ mix run --no-halt                                                                              master
===> Compiling enacl
cc -O3 -std=c99 -arch x86_64 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/Cellar/erlang/21.2.4/lib/erlang/erts-10.2.3/include/ -I /usr/local/Cellar/erlang/21.2.4/lib/erlang/lib/erl_interface-3.10.4/include  -c -o /Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.o /Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c
/Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c:16:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        sodium_init();
        ^~~~~~~~~~~
/Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c:285:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        crypto_box(result.data, padded_msg.data, padded_msg.size, nonce.data, pk.data, sk.data);
        ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c:350:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        crypto_box_beforenm(k.data, pk.data, sk.data);
        ^~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c:1093:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        crypto_kx_server_session_keys(rx.data, tx.data, server_pk.data, server_sk.data, client_pk.data);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c:1121:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        crypto_kx_client_session_keys(rx.data, tx.data, client_pk.data, client_sk.data, server_pk.data);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.c:686:14: warning: unused function 'enif_crypto_shorthash_BYTES' [-Wunused-function]
ERL_NIF_TERM enif_crypto_shorthash_BYTES(ErlNifEnv *env, int argc, ERL_NIF_TERM const argv[]) {
             ^
6 warnings generated.
cc /Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/enacl_nif.o -arch x86_64 -flat_namespace -undefined suppress -shared -L /usr/local/Cellar/erlang/21.2.4/lib/erlang/lib/erl_interface-3.10.4/lib -lerl_interface -lei -lsodium -o /Users/yan/Documents/Projects/PeerDNS/deps/enacl/c_src/../priv/enacl_nif.so
warning: String.strip/1 is deprecated. Use String.trim/1 instead
  /Users/yan/Documents/Projects/PeerDNS/deps/poison/mix.exs:4

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated. Use Integer.to_charlist/2 instead
  lib/poison/encoder.ex:173

Generated poison app
===> Compiling cowlib
===> Compiling cowboy
==> mime
Compiling 2 files (.ex)
Generated mime app
===> Compiling ibrowse
==> httpotion
Compiling 1 file (.ex)
Generated httpotion app
==> plug_crypto
Compiling 4 files (.ex)
Generated plug_crypto app
==> plug
Compiling 1 file (.erl)
Compiling 38 files (.ex)
warning: System.stacktrace/0 outside of rescue/catch clauses is deprecated. If you want to support only Elixir v1.7+, you must access __STACKTRACE__ inside a rescue/catch. If you want to support earlier Elixir versions, move System.stacktrace/0 inside a rescue/catch
  lib/plug/conn/wrapper_error.ex:23

Generated plug app
==> plug_cowboy
Compiling 5 files (.ex)
Generated plug_cowboy app
==> cors_plug
Compiling 1 file (.ex)
Generated cors_plug app
==> peerdns
Compiling 13 files (.ex)
warning: default arguments in http_get!/3 are never used
  lib/peerdns/sync.ex:285

Generated peerdns app
20:56:25.602 [info]  Starting pull from fc18:e736:105d:d49a:2ab5:14a2:698f:7021 with cutoff 0.05...
20:56:25.613 [info]  Application peerdns exited: PeerDNS.Application.start(:normal, []) returned an error: shutdown: failed to start child: PeerDNS.DNSServer
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :eacces}
            (peerdns) lib/peerdns/dns_server.ex:14: anonymous fn/2 in PeerDNS.DNSServer.init/1
            (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
            (peerdns) lib/peerdns/dns_server.ex:12: PeerDNS.DNSServer.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application peerdns: PeerDNS.Application.start(:normal, []) returned an error: shutdown: failed to start child: PeerDNS.DNSServer
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :eacces}
            (peerdns) lib/peerdns/dns_server.ex:14: anonymous fn/2 in PeerDNS.DNSServer.init/1
            (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
            (peerdns) lib/peerdns/dns_server.ex:12: PeerDNS.DNSServer.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by Alexis211** [comment]
Thanks for your report. That error is because you are not allowed to run a server on port 53 (DNS). Your solutions are either to run on another port, but then you cannot use PeerDNS as your regular DNS server, or find a way to bind unprivileged programs to privileged ports. I don't know how you would do that on macOS, if you find a solution please tell me and I'll add it to the readme. In the meantime, I'll make a better error message.

**Comment by yangm97** [comment]
It seems like cjdns starts up as root but then drops permissions to nobody. But indeed, starting up as root seems to have worked. I get a bunch of errors in the log but name resolution seems to be fine afaict.

```
11:09:00.776 [error] Process #PID<0.414.0> raised an exception
** (MatchError) no match of right hand side value: ["local"]
    (peerdns) lib/peerdns/dns_server.ex:47: PeerDNS.DNSServer.get_response/1
    (peerdns) lib/peerdns/dns_server.ex:33: anonymous fn/2 in PeerDNS.DNSServer.handle/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (peerdns) lib/peerdns/dns_server.ex:32: PeerDNS.DNSServer.handle/1
    (peerdns) lib/peerdns/dns_server.ex:25: anonymous fn/4 in PeerDNS.DNSServer.handle_info/2
11:10:23.089 [error] Process #PID<0.430.0> raised an exception
** (MatchError) no match of right hand side value: ["local"]
    (peerdns) lib/peerdns/dns_server.ex:47: PeerDNS.DNSServer.get_response/1
    (peerdns) lib/peerdns/dns_server.ex:33: anonymous fn/2 in PeerDNS.DNSServer.handle/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (peerdns) lib/peerdns/dns_server.ex:32: PeerDNS.DNSServer.handle/1
    (peerdns) lib/peerdns/dns_server.ex:25: anonymous fn/4 in PeerDNS.DNSServer.handle_info/2
```

**Comment by yangm97** [comment]
My guess is that it's related to bonjour/avahi/mDNS.

**Comment by Alexis211** [comment]
I think the "local" error has been fixed, can you tell me if you still have it with the latest version?
The config file has changed a little so you will have to merge the new config.exs.sample in your current config.exs (or just copy it if you didn't do any changes).

**Comment by yangm97** [comment]
Been running it for the last few minutes, looks like I can't trigger the "local" error again. So far so good.
