### ISSUE TITLE
Freaking out when computer sleeps/interface down/missing cjdns/internet connectivity

### ISSUE THREAD

**Issue by yangm97** [p2pstuff/PeerDNS#5]
```
12:15:59.686 [error] Process #PID<0.1800.0> raised an exception
** (MatchError) no match of right hand side value: {:error, :enetdown}
    (peerdns) lib/peerdns/dns_server.ex:135: PeerDNS.DNSServer.resolve_outside/2
    (peerdns) lib/peerdns/dns_server.ex:45: anonymous fn/2 in PeerDNS.DNSServer.handle/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (peerdns) lib/peerdns/dns_server.ex:44: PeerDNS.DNSServer.handle/1
    (peerdns) lib/peerdns/dns_server.ex:37: anonymous fn/4 in PeerDNS.DNSServer.handle_info/2
12:15:59.787 [error] Process #PID<0.1801.0> raised an exception
** (MatchError) no match of right hand side value: {:error, :eaddrnotavail}
    (peerdns) lib/peerdns/dns_server.ex:135: PeerDNS.DNSServer.resolve_outside/2
    (peerdns) lib/peerdns/dns_server.ex:45: anonymous fn/2 in PeerDNS.DNSServer.handle/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (peerdns) lib/peerdns/dns_server.ex:44: PeerDNS.DNSServer.handle/1
    (peerdns) lib/peerdns/dns_server.ex:37: anonymous fn/4 in PeerDNS.DNSServer.handle_info/2
12:15:59.797 [error] Process #PID<0.1802.0> raised an exception
** (MatchError) no match of right hand side value: {:error, :enetunreach}
    (peerdns) lib/peerdns/dns_server.ex:135: PeerDNS.DNSServer.resolve_outside/2
    (peerdns) lib/peerdns/dns_server.ex:45: anonymous fn/2 in PeerDNS.DNSServer.handle/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (peerdns) lib/peerdns/dns_server.ex:44: PeerDNS.DNSServer.handle/1
    (peerdns) lib/peerdns/dns_server.ex:37: anonymous fn/4 in PeerDNS.DNSServer.handle_info/2
```

**Comment by Alexis211** [comment]
Fixed.
